add ex_rate db
valitydev/rate-boss pull request #9
Opened 2023-12-05 14:45 UTC by ggmaleva

2023-12-07 13:06 UTC, vitaxa requested changes

2023-12-07 13:06 UTC, vitaxa commented on src/main/resources/db/migration/V2__add_ex_rate.sql
> +
Пробел стригерил, прости)

2023-12-07 13:06 UTC, vitaxa commented on src/test/kotlin/dev/vality/rateboss/dao/ExRateDaoImplTest.kt
> +        firstExRate.rateTimestamp = LocalDateTime.now()
Можно в apply завернуть такое, ну и везде по коду. Мелочь, а приятно

2023-12-07 13:06 UTC, vitaxa commented on src/main/resources/db/migration/V2__add_ex_rate.sql
> +    id                                 BIGSERIAL PRIMARY KEY,
Есть такое ощущение, что мы можем тут сделать composite primary key. Взяв source_currency_symbolic_code и destination_currency_symbolic_code

2023-12-07 13:06 UTC, vitaxa commented on src/main/kotlin/dev/vality/rateboss/job/ExchangeGrabberJob.kt
> +        exchangeDaoService.saveExchangeRates(currencySymbolCode, currencyExponent.toShort(), exchangeRates)
Если получится отправить event в кафку, но сохранение в базу зафейлится - ничего страшного? Чтоб сделать поддержку консистентности - это сложно. Просто уточняю, на всякий, мне кажется тут это не так критично.

2023-12-07 13:06 UTC, vitaxa commented on src/main/kotlin/dev/vality/rateboss/service/ExchangeDaoService.kt
> +        log.debug("Try to save exRate batch {}", exRates)
Можно это в один debug объединить. Мне кажется одного info сообщения внизу достаточно

2023-12-07 13:06 UTC, vitaxa commented on src/main/kotlin/dev/vality/rateboss/job/ExchangeGrabberJob.kt
> +        exchangeDaoService.saveExchangeRates(currencySymbolCode, currencyExponent.toShort(), exchangeRates)
Можно еще в try catch обернуть чтоб ошибку залогировать, кажется она может потеряться, лишним не будет короч.

2023-12-07 13:06 UTC, vitaxa commented on src/main/resources/db/migration/V2__add_ex_rate.sql
> +    created_at                         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() at time zone 'utc'),
А там нужно и created_at и rate_timestamp? Просто выглядит так что достаточно rate_timestamp, возможно я что-то упускаю

2023-12-07 14:08 UTC, ggmaleva commented on src/main/kotlin/dev/vality/rateboss/job/ExchangeGrabberJob.kt
> +        exchangeDaoService.saveExchangeRates(currencySymbolCode, currencyExponent.toShort(), exchangeRates)
Да, обернуть пождалуй стоит для информативности. А если не обновится какая-то валюта, имхо не критично, потом обновится. Будет небольшой лаг.

2023-12-07 14:16 UTC, ggmaleva commented on src/main/resources/db/migration/V2__add_ex_rate.sql
> +    created_at                         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() at time zone 'utc'),
> А там нужно и created_at и rate_timestamp? Просто выглядит так что достаточно rate_timestamp, возможно я что-то упускаю

Да в целом необязательно. Тут я думал некий аудит добавить, чтоб понимать, когда прилетел курс изначально. Но сейчас думаю, что ты прав. Выглядит излишним. Эту информацию можно будет проверить через daway.

2023-12-07 14:22 UTC, ggmaleva commented on src/main/resources/db/migration/V2__add_ex_rate.sql
> +    id                                 BIGSERIAL PRIMARY KEY,
> Есть такое ощущение, что мы можем тут сделать composite primary key. Взяв source_currency_symbolic_code и destination_currency_symbolic_code

Больше люблю суррогатные ключи. Когда делал ключи из бизнес полей, всегда была какая-то ... неразбериха. Я б оставил просто уникальность для них как сейчас.

2023-12-08 07:24 UTC, vitaxa approved these changes

2023-12-08 08:15 UTC, merged